### PR TITLE
atarv - Completed

### PR DESCRIPTION
**Pull request by atarv**
Included solutions to all 31 problems. I had to touch the JSON-file in `/src/res/` because I couldn't get my program to work otherwise. I think extraneous commas aren't even allowed in JSON by specification.

I suggest you install Haskell with [stack](https://docs.haskellstack.org/en/stable/README/).

Many thanks to the organizers! Happy new year! :fireworks:

### CODE REVIEW

**Comment by mahavisvanathan** [comment]
Great job completing all the questions !!
Fill up the following details to receive your certificate :
**Full name :**
**E-mail ID :**
**Organisation/ University :**

**Comment by atarv** [comment]
Thanks!

Full name: Aleksi Tarvainen
E-mail ID: a.aleksi.tarvainen@student.jyu.fi
Organisation/University: University of Jyväskylä

**Comment by K-Kraken** [comment]
Congratulations @atarv ! 🥇 Your PR will go under review and will be merged if it passes our validations. Your Status will also be mailed to you soon 😄

**Comment by mahavisvanathan** [comment]
@atarv All the extra files except your 31 solutions will be removed and will be merged to the repository. 
**Happy coding!**

**Pull request merged**
